name: Playwright CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install root deps
        run: npm install

      - name: Install backend deps
        run: |
          cd api
          npm install

      - name: Install frontend deps
        run: |
          cd frontend
          npm install

      - name: Install Playwright Browsers
        run: npx --yes playwright install --with-deps

      - name: Run tests
        run: npm run test:all